language: ruby
rvm:
 - 2.5.7
 - 2.6.5
 - 2.7.1
 - jruby
jobs:
  include:
    - stage: gem release
      rvm: 2.6.5
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          tags: true