name: Ruby Gem CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5.7
          - 2.6.5
          - 2.7.1
          - 3.1.6
          - 3.2.6
          - 3.3.6
          - jruby
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake

  release:
    name: Release Gem
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/') # Ensure this runs only on tag creation
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Authenticate with RubyGems
        run: echo "::add-mask::$RUBYGEMS_API_KEY"
      - name: Push Gem to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gem install bundler
          bundle install
          gem build *.gemspec
          gem push *.gem
